// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using TripGenius.Data;

#nullable disable

namespace TripGenius.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408000000_AddTripUserFields")]
    partial class AddTripUserFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            // Model snapshot handled by ApplicationDbContextModelSnapshot
#pragma warning restore 612, 618
        }
    }
}
