// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripGenius.Data;

#nullable disable

namespace TripGenius.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260503113738_UpdatePasswordReset")]
    partial class UpdatePasswordReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripGenius.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(455),
                            NumberOfPeople = 2,
                            Status = "Confirmed",
                            TotalAmount = 20000m,
                            TripId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(459),
                            NumberOfPeople = 1,
                            Status = "Pending",
                            TotalAmount = 15000m,
                            TripId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TripGenius.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("TripGenius.Models.PasswordReset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.ToTable("PasswordResets", (string)null);
                });

            modelBuilder.Entity("TripGenius.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 20000m,
                            BookingId = 1,
                            PaymentDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(551),
                            PaymentMethod = "UPI",
                            Status = "Success"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15000m,
                            BookingId = 2,
                            PaymentDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(554),
                            PaymentMethod = "Card",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("TripGenius.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminReply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReplyDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Amazing trip!",
                            CreatedAt = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(578),
                            Rating = 5,
                            Status = "Approved",
                            TripId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Good experience",
                            CreatedAt = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(580),
                            Rating = 4,
                            Status = "Pending",
                            TripId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TripGenius.Models.SavedTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("SavedTrips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 11, 37, 37, 535, DateTimeKind.Utc).AddTicks(422),
                            TripId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 3, 11, 37, 37, 535, DateTimeKind.Utc).AddTicks(424),
                            TripId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("TripGenius.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BookingConfirmations")
                        .HasColumnType("bit");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("Encryption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FixedFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LoginAlerts")
                        .HasColumnType("bit");

                    b.Property<bool>("NewUserRegistration")
                        .HasColumnType("bit");

                    b.Property<bool>("PaymentAlerts")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProcessingFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ReviewNotifications")
                        .HasColumnType("bit");

                    b.Property<string>("SMTPHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SMTPPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SMTPPort")
                        .HasColumnType("int");

                    b.Property<string>("SMTPUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorAuth")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingConfirmations = true,
                            ContactEmail = "support@trip.com",
                            Currency = "INR",
                            CurrencySymbol = "₹",
                            EmailNotifications = true,
                            FixedFee = 10m,
                            LoginAlerts = false,
                            NewUserRegistration = true,
                            PaymentAlerts = true,
                            Phone = "7777777777",
                            ProcessingFee = 2m,
                            ReviewNotifications = true,
                            SiteDescription = "Travel booking system",
                            SiteName = "TripGenius",
                            TwoFactorAuth = false
                        });
                });

            modelBuilder.Entity("TripGenius.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 0m,
                            CreatedAt = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(384),
                            Description = "Enjoy beaches",
                            Destination = "Goa",
                            DurationDays = 3,
                            EndDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(384),
                            IsSaved = false,
                            Price = 10000m,
                            StartDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(383),
                            Status = "Active",
                            Title = "Goa Beach Trip",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            Budget = 0m,
                            CreatedAt = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(392),
                            Description = "Mountain trip",
                            Destination = "Manali",
                            DurationDays = 5,
                            EndDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(391),
                            IsSaved = false,
                            Price = 15000m,
                            StartDate = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(391),
                            Status = "Active",
                            Title = "Manali Adventure",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("TripGenius.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalSpent")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TripsCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(174),
                            Email = "admin@trip.com",
                            Name = "Admin User",
                            PasswordHash = "123456",
                            Phone = "9999999999",
                            Role = "Admin",
                            Status = "Active",
                            TotalSpent = 0m,
                            TripsCount = 5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 3, 17, 7, 37, 535, DateTimeKind.Local).AddTicks(203),
                            Email = "user@trip.com",
                            Name = "John Doe",
                            PasswordHash = "123456",
                            Phone = "8888888888",
                            Role = "User",
                            Status = "Active",
                            TotalSpent = 20000m,
                            TripsCount = 2
                        });
                });

            modelBuilder.Entity("TripGenius.Models.Booking", b =>
                {
                    b.HasOne("TripGenius.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripGenius.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripGenius.Models.Notification", b =>
                {
                    b.HasOne("TripGenius.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripGenius.Models.Payment", b =>
                {
                    b.HasOne("TripGenius.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("TripGenius.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("TripGenius.Models.Review", b =>
                {
                    b.HasOne("TripGenius.Models.Trip", "Trip")
                        .WithMany("Reviews")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TripGenius.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TripGenius.Models.SavedTrip", b =>
                {
                    b.HasOne("TripGenius.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TripGenius.Models.Booking", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("TripGenius.Models.Trip", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TripGenius.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
